### PR TITLE
fixing bug `Module not context aware` #2

### PR DESCRIPTION
**Pull request by xpepermint**
I tried to change as little as possible. It should work - tested with and without `html5mode=true`.

### CODE REVIEW

**Comment by geekyme** [comment]
thanks @xpepermint tested and it works.

**Comment by xpepermint** [comment]
cool, thanks

**Comment by geekyme** [comment]
published new version to npm. added you as collaborator too. :)

**Comment by xpepermint** [comment]
Thanks man, awesome!

**Pull request merged**
